routes/web.php
<?php

Route::group(['middleware' => ['web']], function () {
    Route::group(['prefix' => 'admin', 'middleware' => 'admin.user', 'as' => 'voyager.'], function () {
        Route::post('documents/settings', '\AlphaIris\Documents\Http\Controllers\DocumentsController@settings')->name('documents.settings');
        Route::post('documents/files', '\AlphaIris\Documents\Http\Controllers\DocumentsController@files')->name('documents.files');
        Route::post('documents/permissions', '\AlphaIris\Documents\Http\Controllers\DocumentsController@permissions')->name('documents.permissions');
        Route::post('documents/new_folder', '\AlphaIris\Documents\Http\Controllers\DocumentsController@new_folder')->name('documents.new_folder');
        Route::post('documents/delete', '\AlphaIris\Documents\Http\Controllers\DocumentsController@delete')->name('documents.delete');
        Route::post('documents/move', '\AlphaIris\Documents\Http\Controllers\DocumentsController@move')->name('documents.move');
        Route::Post('documents/upload', '\AlphaIris\Documents\Http\Controllers\DocumentsController@upload')->name('documents.upload');
        Route::post('documents/rename', '\AlphaIris\Documents\Http\Controllers\DocumentsController@rename')->name('documents.rename');
        Route::get('documents', '\AlphaIris\Documents\Http\Controllers\DocumentsController@index')->name('documents.index');
        Route::get('onedrive/signin', '\AlphaIris\Documents\Http\Controllers\OneDriveController@signin')->name('onedrive.signin');
        Route::get('onedrive/callback', '\AlphaIris\Documents\Http\Controllers\OneDriveController@callback')->name('onedrive.callback');
        Route::get('onedrive/return', '\AlphaIris\Documents\Http\Controllers\OneDriveController@oneDriveReturn')->name('onedrive.return');
    });

    Route::get('documents', '\AlphaIris\Documents\Http\Controllers\Frontend\DocumentsController@index')->name('documents.index');
    Route::get('documents/{path}', '\AlphaIris\Documents\Http\Controllers\Frontend\DocumentsController@show')->name('documents.show')->where('path', '.*');
});

resources/views/admin/index.blade.php
@extends('voyager::master')

@section('page_title', 'Documents')

@section('content')
    <div class="page-content container-fluid">
        @include('voyager::alerts')
        <div class="row">
            <div class="col-md-12">

                <div class="admin-section-title">
                    <h1 class="page-title"><i class="voyager-images"></i>Documents</h1>
                </div>
                <div class="clear"></div>
                <form role="form" class="form-edit-add" action="{{ route('voyager.documents.settings') }}" method="POST" enctype="multipart/form-data">
                    <div class="form-group  col-md-12 ">                                   
                        <label class="control-label" for="name">Allow Access To</label>
                        <div>
                            @foreach($roles as $role)
                                <input type="checkbox" {{ in_array($role['id'],app('documents')->role_ids) ? 'checked' : '' }} name="role_id[]" value="{{ $role['id']}}">{{$role['label']}}<br/>
                            @endforeach
                            <input type="checkbox" {{ app('documents')->allow_guests ? 'checked' : '' }} name="allow_guests" value="true" />Allow Guests<br/>
                        </div>

                    </div>
                    {!!csrf_field()!!}
                    <button type="submit" class="btn btn-primary">Save Settings</button>
                </form>
                <div id="filemanager">
                    <media-manager
                        base-path="{{ setting('documents.storage-path', '/') }}"
                        files-url="{{ route('voyager.documents.files')}}"                        
                        new-folder-route="{{ route('voyager.documents.new_folder') }}" 
                        delete-route="{{ route('voyager.documents.delete') }}" 
                        move-route="{{ route('voyager.documents.move') }}"             
                        upload-route="{{ route('voyager.documents.upload') }}" 
                        rename-route="{{ route('voyager.documents.rename') }}" 
                        :allow-public-urls="false" 
                        :allow-permissions="true" 
                        :show-folders="true"
                        :allow-upload="true"
                        :allow-move="true"
                        :allow-delete="true"
                        :allow-create-folder="true"
                        :allow-rename="true"
                        :allow-crop="false"
                        permissions-url="{{ route('voyager.documents.permissions') }}" 
                        :details="{{ json_encode(['roles' => $roles, 'thumbnails' => config('voyager.media.thumbnails', []), 'watermark' => config('voyager.media.watermark', (object)[])]) }}"
                        ></media-manager>
                </div>
            </div><!-- .row -->
        </div><!-- .col-md-12 -->
    </div><!-- .page-content container-fluid -->
@stop

@section('javascript')
<script>
new Vue({
    el: '#filemanager'
});
</script>
<style>
    #filemanager{
        top: 0px;
    }
</style>
@endsection

resources/views/admin/onedrivereturn.blade.php
@extends('voyager::master')

@section('page_title', 'Documents')

@section('content')
    <div class="page-content container-fluid">
        @include('voyager::alerts')
        
        @if($error)
            <h1>{{$error}}</h1>
            <xmp>
                {{ $errorDescription }}
            </xmp>
        @else
            <h1>You've successfully connected your OneDrive account</h1>
        @endif        
@stop

@section('javascript')

@endsection

resources/views/index.blade.php
@extends('voyager-pages::layouts.default')
@section('meta_title', 'Documents')
@section('page_title', 'Documents')

@push('footer-scripts')
<script>
    window.fileData = {!! json_encode($folderData) !!};

    function displayRoot(){
        renderFolder('root', 'root', window.fileData.files);
        selectFolder('root');
    }

    function createTemplateHtml(templateId, replaceVars){
        let templates = document.getElementById('templates').getElementsByClassName(templateId)[0];
        let html = templates.outerHTML.replace(templateId,'');

        for(var i in replaceVars){
            html = html .replace(new RegExp(i,'g'), replaceVars[i]);
        }
        return html;
    }

    function createFolderHtml(folderId, folderPath, folderName){
        return createTemplateHtml('folderTemplate',{
            folderId: folderId,
            folderPath: folderPath,
            folderName: folderName
        });
    }

    function createDisplayFileHtml(folderId, folderPath, folderName){
        return createTemplateHtml('displayFileTemplate', {
            fileId: folderId,
            filePath: folderPath,
            fileName: folderName
        });
    }

    function createDisplayFolderHtml(folderId, folderPath, folderName){
        return createTemplateHtml('displayFolderTemplate', {
            folderId: folderId,
            folderPath: folderPath,
            folderName: folderName
        });
    }

    function renderFolder(folderId, path, data){
        let folderEl = document.getElementById('folder_' + folderId);
        let filesEl = document.getElementById('docList');

        let foldersHtml = '';
        let filesHtml = '';
        for(var i=0; i < data.length; i++){
            subFolderId = data[i].id;

            if(data[i].type=='dir'){
                foldersHtml += createFolderHtml(subFolderId, data[i].path, data[i].basename);

                filesHtml += createDisplayFolderHtml(subFolderId, data[i].path, data[i].basename);
            }
        }

        for(var i=0; i < data.length; i++){
            if(data[i].type !=='dir'){
                fileId = data[i].id;
                filesHtml += createDisplayFileHtml(fileId, data[i].path, data[i].basename);
            }
        }
        folderEl.innerHTML = foldersHtml;

        if(filesHtml == ''){
            filesHtml = "Hmm, this folder is empty";
        }
        document.getElementById('docList').innerHTML = filesHtml;
    }

    function getFolderData(folderPath, files){
        for(var i=0; i < files.length; i++){
            if(files[i].path == folderPath){
                return files[i];
            }else{
                if(files[i].children){
                    let data = getFolderData(folderPath, files[i].children);
                    if(data){
                        return data;
                    }
                }
            }
        }
        return false;
    }

    function addFolderData(files, data){
        for(var i=0; i < files.length; i++){
            if(files[i].path == data.path){
                files[i].children = data;
                renderFolder(files[i].id, files[i].path, data);
                return true;
            }else{
                if(files[i].children){
                    if(addFolderData(files[i].children, data)){
                        return true;
                    }
                }
            }
        }
        return false;
    }

    function displayFile(fileId, filePath){
        window.open(window.fileData.basePath + filePath);
    }

    function loadFolder(folderPath){
        document.getElementById('docList').innerHTML = '<div class=" flex justify-center items-center"><div class="animate-spin rounded-full h-32 w-32 border-b-2 border-gray-900"></div></div>';
        fetch(window.fileData.basePath + folderPath).then((result) => {
            result.json().then((data)=>{
                data.path = folderPath;
                addFolderData(window.fileData.files, data);
            });
        });
    }

    function toggleFolder(folderId, folderPath){
        folderId = folderId.replace(/\//g,"%2F");
        let folderEl = document.getElementById("folder_" + folderId);
        if(folderEl.classList.contains('hidden')){
            folderEl.classList.remove('hidden');
        }else{
            folderEl.classList.add('hidden');
        }

        let folderData = getFolderData(folderPath, window.fileData.files);
        if(folderData.children){
            renderFolder(folderData.id, folderPath, folderData.children);
        }else{
            loadFolder(folderPath);
        }
        selectFolder(folderId);
    }

    function selectFolder(folderId){
        var sels = document.getElementsByClassName('folders-menu')[0].getElementsByClassName('selected');
        for(var i=0; i < sels.length; i++){
            sels[i].classList.remove('selected');
        }

        document.getElementById('folder_' + folderId + '_link').classList.add('selected');
    }
</script>
@endpush

@section('content')
    <div class="alpha-iris-margin-element documents-page">
        <div class="md:flex documents-display">
            <div class="md:flex-1 md:w-2/5 w-full folders-menu">
                <div class="top-folder">
                    <a id="folder_root_link" class="folder-link selected" href="javascript:displayRoot()">Documents</a>
                </div>
                <div id="folder_root">
                    @foreach($docs as $doc)
                        @if($doc['type'] == 'dir')
                            @include('alpha-iris-documents::partials.menu-folder', [
                                'folderClass' => 'top-folder',
                                'folderId' => urlencode($doc['path']),
                                'folderPath' => $doc['path'],
                                'folderName' => $doc['basename']
                            ])
                        @endif
                    @endforeach
                </div>
            </div>
            <div id="docList" class="md:flex-auto md:w-3/5 w-full folders-display document-list">
                @foreach($docs as $doc)
                    @if($doc['type']=='dir')
                        @include('alpha-iris-documents::partials.display-folder', [
                            'folderClass' => '',
                            'folderId' => urlencode($doc['path']),
                            'folderPath' => $doc['path'],
                            'folderName' => $doc['basename']
                        ])
                    @else
                        @include('alpha-iris-documents::partials.display-file',[
                            'fileClass' => '',
                            'fileId' => urlencode($doc['path']),
                            'filePath' => $doc['path'],
                            'fileName' => $doc['basename']
                        ]);
                    @endif
                @endforeach                
            </div>
        </div>
    </div>

    <div id="templates" class="hidden">
        @include('alpha-iris-documents::partials.menu-folder', [
            'folderClass' => 'folderTemplate',
            'folderId' => 'folderId',
            'folderPath' => 'folderPath',
            'folderName' => 'folderName'
        ])

        @include('alpha-iris-documents::partials.display-folder',[
            'folderClass' => 'displayFolderTemplate',
            'folderId' => 'folderId',
            'folderPath' => 'folderPath',
            'folderName' => 'folderName'
        ])

        @include('alpha-iris-documents::partials.display-file',[
            'fileClass' => 'displayFileTemplate',
            'fileId' => 'fileId',
            'filePath' => 'filePath',
            'fileName' => 'fileName'
        ])        
    </div>
@endsection

resources/views/partials/display-file.blade.php
<div class="{{$fileClass}} display-file">
    <a href="javascript:displayFile('{{ $fileId }}','{{ $filePath }}')">{{ $fileName }}</a>
</div>

resources/views/partials/display-folder.blade.php
<div class="{{$folderClass}} display-folder">
    <a href="javascript:toggleFolder('{{ $folderId }}','{{ $folderPath }}')">{{ $folderName }}</a>
</div>

resources/views/partials/menu-folder.blade.php
<div class="{{ $folderClass }}">
    <a id="folder_{{ $folderId }}_link" class="folder-link" href="javascript:toggleFolder('{{ $folderId}}','{{$folderPath}}')">{{$folderName}}</a>
    <div id="folder_{{ $folderId }}" class="subfolder ml-2 hidden">Loading...</div>
</div>